### ISSUE TITLE
Using this for audio prediction

### ISSUE THREAD

**Issue by robclouth** [ml-jku/hopfield-layers#16]
I need to be able to predict 100 steps into the future of an audio stream.
I have an N x M tensor that is analysed audio, where N is the total length in frames, and M the number of mels per frame.
I would like to use a hopfield layer to predict the next 100 frames from a single input frame.

I could frame it like the simpsons image retrieval task and have the 100 x M blocks of frames as the patterns, and the M input mels as the state, but it appears that the state and pattern have to be the same size.

What's the best way to do this? Is this even the right tool for the job or am I going to quickly hit the storage limit? It's for about 10 mins of audio so N will be about 100000.

**Comment by bschaefl** [comment]
Hi @robclouth,

it is best to contact the authors directly via mail in case of general question about this topic.
