### ISSUE TITLE
Retrieval after training

### ISSUE THREAD

**Issue by robclouth** [ml-jku/hopfield-layers#17]
```
hopfield = Hopfield(
            scaling=beta,

            # do not project layer input
            state_pattern_as_static=True,
            stored_pattern_as_static=True,
            pattern_projection_as_static=True,

            # do not pre-process layer input
            normalize_stored_pattern=False,
            normalize_stored_pattern_affine=False,
            normalize_state_pattern=False,
            normalize_state_pattern_affine=False,
            normalize_pattern_projection=False,
            normalize_pattern_projection_affine=False,

            # do not post-process layer output
            disable_out_projection=True
        )

# and then to retrieve
# Y = stored, x = state
hopfield((Y, x, Y))
```

I've trained the network on MNIST to test storage capacity.
How do I then do retrieval without training again?
I'm expecting a retrieve function like here:
https://github.com/ml-jku/hopfield-layers/blob/e0d856acbb26a429fb2cdf395ef0d1c54b299629/examples/simpsons/models.py#L226

**Comment by bschaefl** [comment]
Hi @robclouth,

the retrieve functionality you refer to is just a single forward pass of the trained Hopfield network. As the retrieved patterns of each head are combined and projected within https://github.com/ml-jku/hopfield-layers/blob/d6d88c80655c1cbec383aeb14b76e6fa51da623e/hflayers/__init__.py#L12-L15 one needs to manually fetch the Hopfield association matrix as well as the projected patterns. This can be achieved by https://github.com/ml-jku/hopfield-layers/blob/d6d88c80655c1cbec383aeb14b76e6fa51da623e/hflayers/__init__.py#L240-L242 and https://github.com/ml-jku/hopfield-layers/blob/d6d88c80655c1cbec383aeb14b76e6fa51da623e/hflayers/__init__.py#L257-L259

To get the retrieved patterns, just reshape the association matrix as well as the projected pattern matrix and apply the former onto the latter. Python-like pseudocode would look like the following:
```python3
xi = hopfield.get_association_matrix(...)
xi = xi.view(*xi.shape[1:])

v = hopfield.get_projected_pattern_matrix(...)
v = v.view(*v.shape[1:])

retrieved_patterns = torch.bmm(xi, v)
```

If there are any remaining questions, feel free to reopen this issue.
