### ISSUE TITLE
Transformer decoder target mask wrong shape error

### ISSUE THREAD

**Issue by kashif** [ml-jku/hopfield-layers#18]
Hello, so I have an encoder-decoder setup with a `tgt_mask` in the decoder as follows:

```py
# enc input [B, C, E]
encoder_association = HopfieldLayer(input_size=E, num_heads=num_heads)
encoder_layer = HopfieldEncoderLayer(
            encoder_association,
            dim_feedforward=E*2,
            dropout=dropout_rate,
            activation=act_type,
        )
transformer_encoder = nn.TransformerEncoder(
            encoder_layer, num_layers=num_encoder_layers
        )

# dec input [B, P, E]
decoder_association_self = HopfieldLayer(
            input_size=E, num_heads=num_heads
    )
decoder_association_cross = HopfieldLayer(
            input_size=P, num_heads=num_heads
        )
decoder_layer = HopfieldDecoderLayer(
            hopfield_association_self=decoder_association_self,
            hopfield_association_cross=decoder_association_cross,
            dim_feedforward=E*2,
            dropout=dropout_rate,
            activation=act_type
        )
transformer_decoder = nn.TransformerDecoder(
            decoder_layer, num_layers=num_decoder_layers
        )

# Transformer
transformer = nn.Transformer(
            d_model=E,
            nhead=num_heads,
            custom_encoder=transformer_encoder,
            custom_decoder=transformer_decoder,
            batch_first=True,
        )
```

I create the mask via:

```
tgt_mask = transformer.generate_square_subsequent_mask(P)
```

And when I run it I get:

```py
 if list(attn_mask.size()) != [1, query.size(0), key.size(0)]:
--> 314                         raise RuntimeError('The size of the 2D attn_mask is not correct.')
```

So for example for `P=28` I have:

```py
attn_mask.shape
torch.Size([1, 28, 28])
```

and query has shape:

```py
query.shape
torch.Size([28, B, E])
```
and key is:

```py
key.shape
torch.Size([1, B, E])
```

for some reason even though the input to the decoder has tensor shapes:

```py
dec_output = transformer.decoder(
            dec_input, # [B, P, E]
            enc_out,  # [B, C, E]
            tgt_mask=tgt_mask, # [P, P]
        )
```

Would you know what I am missing? Thanks!

**Comment by bschaefl** [comment]
Hi @kashif,

for the default encoder-decoder Transformer setting, one has to use `Hopfield` instead of `HopfieldLayer`, as the latter uses learnable parameters as the inputs for the _key_ and _query_. See
https://github.com/ml-jku/hopfield-layers/blob/1497a4d3eaaa0003a8f73484a562329865a61d02/hflayers/__init__.py#L12-L15

and
https://github.com/ml-jku/hopfield-layers/blob/1497a4d3eaaa0003a8f73484a562329865a61d02/hflayers/__init__.py#L619-L623

for more information. Moreover, the input size of `decoder_association_cross` needs to be equal to the number of features of a single instance/token, which is `E` in your case:
```python
decoder_association_cross = Hopfield(input_size=E, num_heads=num_heads)
```

Please let me know, if the issue is resolved.

**Comment by kashif** [comment]
thanks @bschaefl let me check and get back to you!

**Comment by kashif** [comment]
@bschaefl ok so the issue is till there since now my mask is still the same shape: `attn_mask.shape torch.Size([1, P=28, P=28])` and the `query.shape torch.Size([P=28, B, E])` but the key is: `key.shape torch.Size([1, B, E])` and so I still get:

```
if list(attn_mask.size()) != [1, query.size(0), key.size(0)]:
--> 314                         raise RuntimeError('The size of the 2D attn_mask is not correct.')
```

**Comment by kashif** [comment]
@bschaefl yes sorry it works now after replacing *all* the `HopfieldLayer`s by `Hopfield` and the fix thanks!
