### ISSUE TITLE
Simpson's Example Code

### ISSUE THREAD

**Issue by rohan-mehta-1024** [ml-jku/hopfield-layers#19]
Could you please add the code for the Homer/Simpsons example (as shown in the blog post) to this repo?

**Comment by bschaefl** [comment]
Hi @rohan-mehta-1024,

the corresponding code is already present at [examples/simpsons](https://github.com/ml-jku/hopfield-layers/tree/gh-pages/examples/simpsons) of the `gh-pages` branch.
