### ISSUE TITLE
installing hopfield-layers file on colab

### ISSUE THREAD

**Issue by awlayaa** [ml-jku/hopfield-layers#20]
Hi 
when I run this repository on colab, as:
!pip3 install git+https://github.com/ml-jku/hopfield-layers

the next lines showed up:
Collecting git+https://github.com/ml-jku/hopfield-layers
  Cloning https://github.com/ml-jku/hopfield-layers to /tmp/pip-req-build-habi_ez5
  Running command git clone -q https://github.com/ml-jku/hopfield-layers /tmp/pip-req-build-habi_ez5
Requirement already satisfied: torch>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from hopfield-layers==1.0.1) (1.10.0+cu111)
Collecting numpy>=1.20.0
  Using cached numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
ERROR: Package 'hopfield-layers' requires a different Python: 3.7.12 not in '>=3.8.0'

how can I fix it?

**Comment by chumingqian** [comment]
@awlayaa :
            Can  you  use  anaconda ,  create a  python3.8  environment,   and then  try it;
