### ISSUE TITLE
how is it performance in seq2seq task?

### ISSUE THREAD

**Issue by af-74413592** [ml-jku/hopfield-layers#21]

**Comment by af-74413592** [comment]
test in transformerlike-seq2seq task, frankly, it doesn't work.

**Comment by bschaefl** [comment]
Hi @af-74413592,

I cannot quite follow your issue, I'm afraid. If you want to deploy [hopfield-layers](https://github.com/ml-jku/hopfield-layers) in a transformer-like setting, the corresponding implementations https://github.com/ml-jku/hopfield-layers/blob/f56f929c95b77a070ae675ea4f56b6d54d36e730/hflayers/transformer.py#L12-L15 and https://github.com/ml-jku/hopfield-layers/blob/f56f929c95b77a070ae675ea4f56b6d54d36e730/hflayers/transformer.py#L101-L104 are a drop-in replacement for [TransformerEncoderLayer](https://github.com/pytorch/pytorch/blob/b31f58de6fa8bbda5353b3c77d9be4914399724d/torch/nn/modules/transformer.py#L241) and [TransformerDecoderLayer](https://github.com/pytorch/pytorch/blob/b31f58de6fa8bbda5353b3c77d9be4914399724d/torch/nn/modules/transformer.py#L303), respectively.
