### ISSUE TITLE
ModuleNotFoundError: No module named 'dataloader'

### ISSUE THREAD

**Issue by monk1337** [ml-jku/hopfield-layers#5]
Thank you for awesome work.
While Running the code, I am getting this error 
`ModuleNotFoundError: No module named 'dataloader'.`

The second error is

`---> 21 from model import Attention, GatedAttention`

`ModuleNotFoundError: No module named 'model'`

Can you update the repo with these two files please?

**Comment by HRamses** [comment]
> Thank you for awesome work.
> While Running the code, I am getting this error
> `ModuleNotFoundError: No module named 'dataloader'.`
> 
> The second error is
> 
> `---> 21 from model import Attention, GatedAttention`
> 
> `ModuleNotFoundError: No module named 'model'`
> 
> Can you update the repo with these two files please?

Hello monk1337!

Did you download the Attention-based Deep Multiple Instance Learning and added the path like described in the README?

**Comment by monk1337** [comment]
@HRamses  Hi, I didn't see any instructions like that in the README. Please check.

**Comment by HRamses** [comment]
> @HRamses Hi, I didn't see any instructions like that in the README. Please check.

The instructions are here: https://github.com/ml-jku/hopfield-layers/blob/master/examples/mnist_bags/README.md

**Comment by bschaefl** [comment]
Closing issue. Seems to be resolved by directing the issue author to the appropriate README.
