### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by roholazandie** [ml-jku/hopfield-layers#8]
Hi,
Thanks for sharing this amazing work! I look into your code and realized some parts of it especially hopfield_core_forward is very long and hard to read. There are too many nested if and for statements. Is there any plan to make them more readable? Or maybe providing more detailed documentation of what is present in the paper?

**Comment by bschaefl** [comment]
Thanks for your interest in our work!

I can see, that some parts of the source code can be a little bit intimidating. Some functions/classes are based on existing ones of the official PyTorch repository – especially `hopfield_core_forward` you a referring to. We want our implementation to be accessible for those who are already familiar with the related PyTorch implementations, to not "reinvent the wheel" in a way. At this point I want to refer to the corresponding disclaimer section of our [README](https://github.com/ml-jku/hopfield-layers/blob/master/README.md#disclaimer).

Our Hopfield-based implementation is very versatile, so at some point corresponding flags need to be checked and acted upon accordingly. We tried to be as comprehensive as needed but concise as possible with respect to our documentation (please have a look at the corresponding docstrings and inline comments).

From a user's perspective, the interface is [modules/\_\_init\_\_.py](https://github.com/ml-jku/hopfield-layers/blob/79162bee601f861befe17aea97dd1b0c12c6f465/modules/__init__.py), especially

https://github.com/ml-jku/hopfield-layers/blob/79162bee601f861befe17aea97dd1b0c12c6f465/modules/__init__.py#L12-L15

and

https://github.com/ml-jku/hopfield-layers/blob/79162bee601f861befe17aea97dd1b0c12c6f465/modules/__init__.py#L383-L387

There, everything described in the paper can be accessed (please have a look at the corresponding docstrings). Moreover, [appendix C](https://arxiv.org/pdf/2008.02217.pdf) of the paper (page 78 onwards), especially Figure C1 on page 82 might be of help. If you have any specific questions or problems, feel free to contact us.

Last but not least, I want to emphasise, that we're still working on this topic, so the code is still under development and is therefore subject to change.
