### ISSUE TITLE
CUDA produces inconsistent mnist_bas_demo results?

### ISSUE THREAD

**Issue by jabowery** [ml-jku/hopfield-layers#9]
With CUDA my results for the mnist_bas_demo.ipynb differ sometimes substantially from those in the "RESULTS" provided in the last cell of the notebook.  This is true even if I restart the `jupyter` kernel nd re-rereun everything from the top of the notebook.

Here are two runs for each of the models with `args.nocuda = False`:

hf_pooling: Test Set, Loss 0.4946, Test error: 0.2400
hf_pooling: Test Set, Loss 0.7363, Test error: 0.160
gated_attention: Test Set, Loss 0.3561,Test error: 0.800
gated_attention: Test Set, Loss 0.4902,Test error: 0.800
attention: Test Set, Loss 0.4719,Test error: 0.800
attention: Test Set, Loss 0.8885,Test error: 0.2000

With `args.nocuda = True` here are some runs showing the same errors as those in "RESULTS":

hf_pooling: Test Set, Loss 0.4990, Test error: 0.0600
gated_attention: Test Set, Loss 0.6183,Test error: 0.800
attention: Test Set, Loss 0.7787,Test error: 0.1000

**Comment by bschaefl** [comment]
Thanks for trying out our repository and the enclosed Jupyter notebooks!

Closing issue as it is resolved by 853addff5348fc00338bd121fe1059e8b06a0b46.
